import { Geist, Geist_Mono, Open_Sans } from "next/font/google";
import "./globals.css";
import Navbar from "../components/Navbar";
import TopInfoBar from "../components/Topbar";

const openSans = Open_Sans({
  subsets: ["latin"],
  weight: ["400", "600", "700"], // regular, semi-bold, bold
});

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

export const metadata = {
  title: "Sai Ram IT & Infra",
  // description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        // className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        className={`${openSans.className} antialiased`}
      >
        <div className="sticky top-0 z-[99] w-full">
          <TopInfoBar />
          <Navbar />
        </div>
        {children}
      </body>
    </html>
  );
}
